{
 "title": "JWT Pizza Service Production",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "activeUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(authAttempts_successful{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(authAttempts_failed{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(requestCounts_GET{source=\"jwt-pizza-service\"}[1m])) + sum(rate(requestCounts_POST{source=\"jwt-pizza-service\"}[1m])) + sum(rate(requestCounts_DELETE{source=\"jwt-pizza-service\"}[1m])) + sum(rate(requestCounts_PUT{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(requestCounts_DELETE{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(requestCounts_GET{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(requestCounts_POST{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "post"
    },
    {
     "expr": "sum(rate(requestCounts_PUT{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemMetrics_memoryUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemMetrics_cpuUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "latencyMetrics_serviceEndpoint{source=\"jwt-pizza-service\"}",
     "legendFormat": "Service Endpoint"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizzaMetrics_sold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Sold"
    },
    {
     "expr": "pizzaMetrics_creationFailures{source=\"jwt-pizza-service\"}",
     "legendFormat": "Creation Failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzaMetrics_revenue{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "latencyMetrics_pizzaCreation{source=\"jwt-pizza-service\"}",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}